python challenge of create virtualenv
huhuhang/labex-trial pull request #1
Opened 2022-12-01 06:06 UTC by GodsDusk

# PR Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] The lab/challenge structure is correct. See more details in [How to Write a Lab](https://github.com/labex-dev/devops-labs/discussions/3).
- [ ] The format of the lab/challenge is correct. See more details in [Formatting Requirements](https://github.com/labex-dev/devops-labs/discussions/5).
- [ ] I pledge that I did not plagiarize and I did not copy the solution from other sources. See more details in [Honesty Policy](https://github.com/labex-dev/devops-labs/discussions/7).

2022-12-01 06:19 UTC, huhuhang requested changes
建议再丰富一些，写成一个多步骤的挑战，包含创建，移除等更多的 step。还可以将这个 challenge 变化成一个配套的 lab。

我们建议 lab 和 challenge 进行配套，同样的步骤，同样的 skill，只是 lab 直接把操作包含在步骤中，而 challenge 需要用户自己完成。

2022-12-03 09:38 UTC, GodsDusk commented
已添加 lab

2022-12-04 07:42 UTC, huhuhang requested changes
整体无大问题，有一些格式问题进行了标注，并没有标全，相同的地方需要修改。

2022-12-04 07:42 UTC, huhuhang commented on python/lab-python-virtual-env/intro.md
> +The virtual environment is an important concept for python.
专有名词请使用官方大小写，Python

2022-12-04 07:42 UTC, huhuhang commented on python/lab-python-virtual-env/intro.md
> +- assgin python version
请使用 Title Case。

2022-12-04 07:42 UTC, huhuhang commented on python/lab-python-virtual-env/step1.md
> +First，let us to create a python virtual enviroment.
1. 英文需要使用半角标点。
2. enviroment 拼写错误，提交前请使用 grammarly 检查。

2022-12-04 07:42 UTC, huhuhang commented on python/lab-python-virtual-env/finish.md
> +- manage different python virtual environments
如果是 how to do，就保持一致。结尾加标点。

2022-12-04 07:42 UTC, huhuhang commented on python/challenge-python-virtual-env/step1.md
> +Create a python virtual environment.
Python

2022-12-05 01:39 UTC, huhuhang approved these changes

2022-12-05 01:39 UTC, merged

2023-04-17 04:48 UTC, huhuhang commented
Hi, @GodsDusk 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。