add user account management challenge
huhuhang/labex-trial pull request #2
Opened 2022-12-01 11:46 UTC by joker-bai

# PR Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] The lab/challenge structure is correct.
- [ ] The format of the lab/challenge is correct.
- [ ] I pledge that I did not plagiarize and I did not copy the solution from other sources.

See more details in [Contributing Guidelines](https://labex.gitbook.io/contributing-guidelines/).

2022-12-02 06:36 UTC, huhuhang requested changes
1. 图片的相对链接地址，我已经修正了。
2. 标题需要使用 title case 的样式。详见：https://labex.gitbook.io/contributing-guidelines/formatting-and-design-guide#markdown
3. 需要使用 Grammarly 润色一下，会有一些建议和格式问题。

2022-12-02 06:38 UTC, huhuhang commented
建议转写成配套实验，同时估算一下相同 skills 同时提供一组配套 lab/challenge 的时间成本，我们后面可以交流一下。

2022-12-02 06:55 UTC, huhuhang commented
@joker-bai 另外英文句法上可以多变化一些，所有的句子都用相同的开头，会让人看得特别乏味。😂

2022-12-02 07:25 UTC, joker-bai commented
> @joker-bai 另外英文句法上可以多变化一些，所有的句子都用相同的开头，会让人看得特别乏味。😂

好的，我先把走学会了，再来慢慢跑~~

2022-12-02 07:26 UTC, joker-bai commented
> 建议转写成配套实验，同时估算一下相同 skills 同时提供一组配套 lab/challenge 的时间成本，我们后面可以交流一下。

OK，我先整改完challenge

2022-12-02 09:49 UTC, huhuhang approved these changes

2022-12-02 09:50 UTC, merged

2023-04-17 04:48 UTC, huhuhang commented
Hi, @joker-bai 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。