Add lab account management
huhuhang/labex-trial pull request #3
Opened 2022-12-03 04:20 UTC by joker-bai

# PR Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] The lab/challenge structure is correct.
- [ ] The format of the lab/challenge is correct.
- [ ] I pledge that I did not plagiarize and I did not copy the solution from other sources.

See more details in [Contributing Guidelines](https://labex.gitbook.io/contributing-guidelines/).

2022-12-04 07:51 UTC, huhuhang requested changes
内容没大问题，写得很好。

1. lab 不需要 Requirements。
2. 每一个 step 的内容有点多了，step 是最小单元，其实可以拆得细一些，一个 step 能在 3～5 分钟内完成。
3. lab 能够检测的步骤，也需要有 verify 脚本，起到校验学生做没做，并且给到用户交互的感觉。这也就是我们为什么统一了 challenge/lab 的组织结构，二者唯一的区别在于内容的表述方式上。所以 challenge 之前写的 verify 脚本要被复用起来，不要浪费了。😂

2022-12-04 07:51 UTC, huhuhang commented on linux/lab-account-management/intro.md
> +In this challenge, we will introduce how to manage the user account in the Linux platform, such as creating new user accounts, modifying the user account management, and deleting a user account.
In this challenge?

2022-12-04 09:20 UTC, joker-bai commented on linux/lab-account-management/intro.md
> +In this challenge, we will introduce how to manage the user account in the Linux platform, such as creating new user accounts, modifying the user account management, and deleting a user account.
OK，我再改改

2022-12-04 12:13 UTC, joker-bai commented
> 内容没大问题，写得很好。
> 
> 1. lab 不需要 Requirements。
> 2. 每一个 step 的内容有点多了，step 是最小单元，其实可以拆得细一些，一个 step 能在 3～5 分钟内完成。不用担心 step 太碎，step 就是最小颗粒。
> 3. lab 能够检测的步骤，也需要有 verify 脚本，起到校验学生做没做，并且给到用户交互的感觉。这也就是我们为什么统一了 challenge/lab 的组织结构，二者唯一的区别在于内容的表述方式上。所以 challenge 之前写的 verify 脚本要被复用起来，不要浪费了。😂 你可以吧 lab 和 challenge 看作是同样 skills 下的 guided mode 和 challenge mode 2 种不同的学习形式。

——————————————————————————————————

已经修改了 @huhuhang ，麻烦再看看

2022-12-05 01:38 UTC, huhuhang approved these changes

2022-12-05 01:38 UTC, merged

2023-04-17 04:48 UTC, huhuhang commented
Hi, @joker-bai 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。