cat and head command
huhuhang/labex-trial pull request #4
Opened 2022-12-04 05:46 UTC by zxhTom

# PR Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] The lab/challenge structure is correct.
- [ ] The format of the lab/challenge is correct.
- [ ] I pledge that I did not plagiarize and I did not copy the solution from other sources.

See more details in [Contributing Guidelines](https://labex.gitbook.io/contributing-guidelines/).

2022-12-04 08:04 UTC, huhuhang requested changes
整体合格，请注意：

1. 所有的内容，请提交前务必使用 Grammarly 检查。
2. 内容文件夹名称，不要包含 demo，试写也是正式内容。合格会被直接采纳。

2022-12-04 08:04 UTC, huhuhang commented on linux/challenge-demo-operation/step1.md
> +Now ask you to complete the ~/temp/test file retrieval operation.
段落内的路径、代码、需要用行内代码样式。`~/temp/test`

所有的内容中，尽量不要用 test，demo 这种，要正式一些。

2022-12-04 08:04 UTC, huhuhang commented on linux/challenge-demo-operation/step2.md
> +Now please print the first byte of the ～/temp/tests file via the full path.
紧密挨着的内容，尽量变化一下句式。

2022-12-04 08:04 UTC, huhuhang commented on linux/challenge-demo-operation/verify1-2.sh
> +history | grep -E 'cat\s+\-n\s+~/temp/test$|cat\s+\-n\s+test$'
检测的方法和 nice。👍

2022-12-04 08:04 UTC, zxhTom commented
邮件已收到！谢谢配合。

2022-12-05 06:24 UTC, mercury7720 commented on linux/challenge-demo-operation/verify1-2.sh
> +history | grep -E 'cat\s+\-n\s+~/temp/test$|cat\s+\-n\s+test$'
最好不要使用 `history` 命令而是直接读取 `~/.zsh_history` 文件。

2022-12-07 07:13 UTC, huhuhang requested changes
图片标注存在中文。

2022-12-07 07:45 UTC, zxhTom commented on linux/lab-demo-operation/intro.md
> +In this lab, you will learn to use some file operation command that allows you to perform actions such as view the contents of the file, and operator or filter then contents of file.
Fixed

2022-12-07 07:45 UTC, zxhTom commented on linux/challenge-demo-operation/intro.md
> +In this lab, you will learn to use some file operation command that allows you to perform actions such as view the contents of the file, and operator or filter then contents of file.
Fixed

2022-12-07 07:45 UTC, zxhTom commented on linux/challenge-demo-operation/step1.md
> +Now ask you to complete the ~/temp/test file retrieval operation.
Fixed

2022-12-07 07:45 UTC, zxhTom commented on linux/challenge-demo-operation/step2.md
> +Now please print the first byte of the ～/temp/tests file via the full path.
Fixed

2022-12-07 07:45 UTC, zxhTom commented on linux/challenge-demo-operation/verify1-2.sh
> +history | grep -E 'cat\s+\-n\s+~/temp/test$|cat\s+\-n\s+test$'
Fixed

2022-12-07 07:46 UTC, zxhTom commented
> 图片标注存在中文。

Fixed

2022-12-07 08:09 UTC, merged

2023-04-17 04:48 UTC, huhuhang commented
Hi, @zxhTom 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。

2023-04-17 04:48 UTC, zxhTom commented
邮件已收到！谢谢配合。